# Docker file based on centos latest 7, write acustom message

FROM centos:latest
MAINTAINER krishna4charan@gmail.com

RUN useradd -ms /bin/bash test

CMD "echo" "Hello Users this is a basic image"

USER test

